export enum HttpExceptionEnum {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ACTION_DENIED = 'ACTION_DENIED',
  NOT_FOUND = 'NOT_FOUND',
}

export enum RequestExceptionEnum {
  USER_NOT_EXIST = 'USER_NOT_EXIST',
  DEVICE_ACCESS_BY_INVALID_USER = 'DEVICE_ACCESS_BY_INVALID_USER',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
}
