name: CI Test

env:
  MONGODB_URI: ${{ vars.CI_MONGODB_URI }}
  AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
  AUTH0_ISSUER_URL: ${{ secrets.AUTH0_ISSUER_URL }}
  AUTH0_TOKEN_SIGN_ALG: ${{ secrets.AUTH0_TOKEN_SIGN_ALG }}
  AUTH0_MACHINE_CLIENT_ID: ${{ secrets.AUTH0_MACHINE_CLIENT_ID }}
  AUTH0_MACHINE_CLIENT_SECRECT: ${{ secrets.AUTH0_MACHINE_CLIENT_SECRECT }}

on:
  workflow_dispatch:
  push:
    branches:
      - feat/**
      - feature/**
      - fix/**

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye
      env:
        NODE_ENV: development
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm i

      - name: Check lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run test:ci


      - name: Run test e2e
        run: npm run test:e2e

