name: Vercel Production Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
  AUTH0_ISSUER_URL: ${{ secrets.AUTH0_ISSUER_URL }}
  AUTH0_TOKEN_SIGN_ALG: ${{ secrets.AUTH0_TOKEN_SIGN_ALG }}

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Nest CLI
        run: npm install --global @nestjs/cli@latest

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm i

      - name: Deploy preview to Vercel
        run: npm run deploy:prod
